name: Update README  # Nombre del workflow (lo verás en la pestaña Actions de GitHub)

on:
  schedule:
    - cron: "*/12 * * * *"  # Ejecuta el workflow automáticamente cada 12 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub (botón "Run workflow")

jobs:
  build:
    runs-on: ubuntu-latest  # Define el sistema operativo donde se ejecutará (máquina virtual de Ubuntu)
    name: Update Profile README  # Nombre del job

    steps:
      - uses: actions/checkout@v2.3.4  # Descarga el repositorio para poder trabajar con sus archivos

      - uses: jamesgeorge007/github-activity-readme@master  # Acción que actualiza la actividad reciente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticación para acceder a la API de GitHub